Resources:
  IdentityBearer:
    Type: AWS::IAM::Role
    Properties:
      RoleName: idp-terraform-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref AWS::AccountId
            Action:
              - sts:AssumeRole
              - sts:SetContext
      Policies:
        - PolicyName: AllowS3DataAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: s3:GetDataAccess
                Resource: "*"

Outputs:
  IdentityBearer:
    Value: !GetAtt IdentityBearer.Arn
